export default {
	char: [
		{
	  	  id: "bmw1",
	  	  model: "BMW 730i",
	  	  img: " ",
	  	  data: "2015",
	  	  country: "Germany",
	  	  doors: "4",
	  	  drive: "задний",
	  	  cpp: "автоматическая",
	  	  maxSpeed: "250",
	  	  speedTo100: "6,2",
	  	  mark: "bmw"
		},
		{
	  	  id: "bmw2",
	  	  model: "BMW M760Li xDrive",
	  	  img: " ",
	  	  data: "2013",
	  	  country: "Germany",
	  	  doors: "4",
	  	  drive: "задний",
	  	  cpp: "автоматическая",
	  	  maxSpeed: "240",
	  	  speedTo100: "4,2",
	  	  mark: "bmw"
		},
		{
	  	  id: "bmw3",
	  	  model: "BMW M3",
	  	  img: " ",
	  	  data: "2012",
	  	  country: "Germany",
	  	  doors: "4",
	  	  drive: "задний",
	  	  cpp: "автоматическая",
	  	  maxSpeed: "280",
	  	  speedTo100: "8,2",
	  	  mark: "bmw"
		},
		{
	  	  id: "bg1",
	  	  model: "Bugatti Chiron",
	  	  img: " ",
	  	  data: "2013",
	  	  country: "France",
	  	  doors: "2",
	  	  drive: "полный",
	  	  cpp: "автоматическая",
	  	  maxSpeed: "350",
	  	  speedTo100: "3,2",
	  	  mark: "bugatti"
		},
		{
	  	  id: "bg2",
	  	  model: "Bugatti Veyron Grand Sport",
	  	  img: " ",
	  	  data: "2005",
	  	  country: "France",
	  	  doors: "2",
	  	  drive: "полный",
	  	  cpp: "автоматическая",
	  	  maxSpeed: "407",
	  	  speedTo100: "2,5",
	  	  mark: "bugatti"
		},
		{
	  	  id: "bg3",
	  	  model: "Bugatti EB218",
	  	  img: " ",
	  	  data: "2010",
	  	  country: "France",
	  	  doors: "2",
	  	  drive: "полный",
	  	  cpp: "автоматическая",
	  	  maxSpeed: "350",
	  	  speedTo100: "5,6",
	  	  mark: "bugatti"
		},
		{
	  	  id: "dod1",
	  	  model: "VIPER",
	  	  img: " ",
	  	  data: "2012",
	  	  country: "Usa",
	  	  doors: "2",
	  	  drive: "полный",
	  	  cpp: "механическая 6 ст",
	  	  maxSpeed: "350",
	  	  speedTo100: "4,5",
	  	  mark: "dodge"
		},
		{
	  	  id: "dod2",
	  	  model: "DART",
	  	  img: " ",
	  	  data: "2005",
	  	  country: "Usa",
	  	  doors: "2",
	  	  drive: "полный",
	  	  cpp: "автоматическая",
	  	  maxSpeed: "407",
	  	  speedTo100: "6,5",
	  	  mark: "dodge"
		},
		{
	  	  id: "dod3",
	  	  model: "Charger",
	  	  img: " ",
	  	  data: "2010",
	  	  country: "Usa",
	  	  doors: "2",
	  	  drive: "полный",
	  	  cpp: "автоматическая",
	  	  maxSpeed: "350",
	  	  speedTo100: "3,6",
	  	  mark: "dodge"
		},
		{
	  	  id: "lam1",
	  	  model: "Countach",
	  	  img: " ",
	  	  data: "2012",
	  	  country: "Italy",
	  	  doors: "2",
	  	  drive: "полный",
	  	  cpp: "механическая 6 ст",
	  	  maxSpeed: "350",
	  	  speedTo100: "4,5",
	  	  mark: "lamboghini"
		},
		{
	  	  id: "lam2",
	  	  model: "Diablo",
	  	  img: " ",
	  	  data: "2005",
	  	  country: "Italy",
	  	  doors: "2",
	  	  drive: "полный",
	  	  cpp: "автоматическая",
	  	  maxSpeed: "330",
	  	  speedTo100: "3,5",
	  	  mark: "lamboghini"
		},
		{
	  	  id: "lam3",
	  	  model: "Gallardo Spyder",
	  	  img: " ",
	  	  data: "2010",
	  	  country: "Italy",
	  	  doors: "2",
	  	  drive: "полный",
	  	  cpp: "автоматическая",
	  	  maxSpeed: "350",
	  	  speedTo100: "3,6",
	  	  mark: "lamboghini"
		},
		{
	  	  id: "lot1",
	  	  model: "Evora",
	  	  img: " ",
	  	  data: "2012",
	  	  country: "England",
	  	  doors: "2",
	  	  drive: "полный",
	  	  cpp: "автоматическая",
	  	  maxSpeed: "220",
	  	  speedTo100: "7,5",
	  	  mark: "lotus"
		},
		{
	  	  id: "lot2",
	  	  model: "Exige",
	  	  img: " ",
	  	  data: "2005",
	  	  country: "England",
	  	  doors: "2",
	  	  drive: "полный",
	  	  cpp: "автоматическая",
	  	  maxSpeed: "260",
	  	  speedTo100: "6,5",
	  	  mark: "lotus"
		},
		{
	  	  id: "lot3",
	  	  model: "Elise",
	  	  img: " ",
	  	  data: "2010",
	  	  country: "England",
	  	  doors: "2",
	  	  drive: "полный",
	  	  cpp: "автоматическая",
	  	  maxSpeed: "270",
	  	  speedTo100: "8,0",
	  	  mark: "lotus"
		},
		{
	  	  id: "mer1",
	  	  model: "CLS-CLASS AMG",
	  	  img: " ",
	  	  data: "2012",
	  	  country: "Germany",
	  	  doors: "5",
	  	  drive: "полный",
	  	  cpp: "автоматическая",
	  	  maxSpeed: "220",
	  	  speedTo100: "7,5",
	  	  mark: "mercedes"
		},
		{
	  	  id: "mer2",
	  	  model: "E-CLASS AMG",
	  	  img: " ",
	  	  data: "2005",
	  	  country: "Germany",
	  	  doors: "4",
	  	  drive: "полный",
	  	  cpp: "автоматическая",
	  	  maxSpeed: "260",
	  	  speedTo100: "6,5",
	  	  mark: "mercedes"
		},
		{
	  	  id: "mer3",
	  	  model: "S-CLASS AMG",
	  	  img: " ",
	  	  data: "2010",
	  	  country: "Germany",
	  	  doors: "2",
	  	  drive: "полный",
	  	  cpp: "автоматическая",
	  	  maxSpeed: "270",
	  	  speedTo100: "4,0",
	  	  mark: "mercedes"
		},
		{
	  	  id: "rol1",
	  	  model: "Ghost",
	  	  img: " ",
	  	  data: "2012",
	  	  country: "England",
	  	  doors: "4",
	  	  drive: "полный",
	  	  cpp: "автоматическая",
	  	  maxSpeed: "220",
	  	  speedTo100: "7,5",
	  	  mark: "rolls"
		},
		{
	  	  id: "rol2",
	  	  model: "Wraith",
	  	  img: " ",
	  	  data: "2005",
	  	  country: "England",
	  	  doors: "4",
	  	  drive: "полный",
	  	  cpp: "автоматическая",
	  	  maxSpeed: "260",
	  	  speedTo100: "6,5",
	  	  mark: "rolls"
		},
		{
	  	  id: "rol3",
	  	  model: "Phantom",
	  	  img: " ",
	  	  data: "2010",
	  	  country: "England",
	  	  doors: "4",
	  	  drive: "полный",
	  	  cpp: "автоматическая",
	  	  maxSpeed: "270",
	  	  speedTo100: "5,8",
	  	  mark: "rolls"
		},
		{
	  	  id: "tsl1",
	  	  model: "Roadster",
	  	  img: " ",
	  	  data: "2012",
	  	  country: "Usa",
	  	  doors: "4",
	  	  drive: "полный",
	  	  cpp: "автоматическая",
	  	  maxSpeed: "280",
	  	  speedTo100: "2,9",
	  	  mark: "tesla"
		},
		{
	  	  id: "tsl2",
	  	  model: "Model S",
	  	  img: " ",
	  	  data: "2005",
	  	  country: "Usa",
	  	  doors: "4",
	  	  drive: "полный",
	  	  cpp: "автоматическая",
	  	  maxSpeed: "260",
	  	  speedTo100: "3,5",
	  	  mark: "tesla"
		},
		{
	  	  id: "tsl3",
	  	  model: "Model 3",
	  	  img: " ",
	  	  data: "2010",
	  	  country: "Usa",
	  	  doors: "2",
	  	  drive: "полный",
	  	  cpp: "автоматическая",
	  	  maxSpeed: "320",
	  	  speedTo100: "3,8",
	  	  mark: "tesla"
		},
	]
}